# Generated by Django 4.0.6 on 2022-08-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='project',
        ),
    ]
