# Generated by Django 4.0.6 on 2022-08-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='describ',
        ),
    ]
