# Generated by Django 4.0.6 on 2022-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_describtion_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fearured_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
