# Generated by Django 4.0.6 on 2022-09-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nick_name',
            new_name='short_intro',
        ),
    ]
