# Generated by Django 3.1.5 on 2023-10-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/user-profile.gif', null=True, upload_to='profiles/'),
        ),
    ]
