# Generated by Django 3.1.5 on 2023-10-27 00:30

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231026_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
